version: '3'

services:
  netmaulserver:
    build: .
    container_name: "netmaulserver"
    command: ["/go/src/github.com/netm4ul/netm4ul/netm4ul","-server"]
    ports:
      - 8080:8080

  netmaulclient:
    container_name: "netmaulclient"
    build: .
    command: ["/go/src/github.com/netm4ul/netm4ul/netm4ul"]

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      # MONGODB_USER: user
      # MONGODB_PASS: pass
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
